services:
  - type: web
    name: medcare-backend
    env: node
    buildCommand: chmod +x build-render.sh && ./build-render.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    healthCheckPath: /health
    autoDeploy: true 